### ISSUE TITLE
Spotify is Blocked

### ISSUE THREAD

**Issue by Osaka-Classified** [renagamer101/renagamer101.github.io#1]
Spotify is blocked I need links please (on the website aswell)

**Comment by renagamer101** [comment]
yes i know i need to figure out a way to unblock i might add a subdomain

**Comment by Osaka-Classified** [comment]
Okay, let me know if I can help you in any way.

**Comment by renagamer101** [comment]
could u check if its blocked anymore
it shouldnt be blocked any more

**Comment by Osaka-Classified** [comment]
It’s blocked now

**Comment by renagamer101** [comment]
still?

**Comment by RetroWonder** [comment]
Use like an open-source rammerhead instance, that may work?

**Comment by schooldev49** [comment]
This is an issue with the Ultraviolet rewriting scripts

**Comment by renagamer101** [comment]
Yeah but I don't have a rammerhead

**Comment by renagamer101** [comment]
Nvm
